force-app/main/default/objects/Jira_Project__c/Jira_Project__c.object-meta.xml
<CustomObject>
    <label>Jira Project</label>
    <nameField>
        <label>Jira Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jira Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Jira_Project__c/fields/Project_Key__c.field-meta.xml
<CustomField>
    <fullName>Project_Key__c</fullName>
    <externalId>true</externalId>
    <label>Project Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProjectUpdatedProcessor.cls
public without sharing class ProjectUpdatedProcessor implements WebhookEventProcessor, Queueable {

    private Map<String, Object> payload;

    public ProjectUpdatedProcessor(Map<String, Object> payload){
        this.payload = payload;
    }

    /**
     * @description Process an project_updated event
     * @param payload The webhook payload
     */
    public void process(Map<String, Object> payload){
        try{
            Map<String, Object> projectData = (Map<String, Object>)payload.get('project');
            String projectKey = (String)projectData.get('key');

            Jira_Project__c queriedProject = [
                SELECT 
                Project_Name__c,
				Project_Key__c,
				Description__c
                FROM Jira_Project__c
                WHERE Project_Key__c = :projectKey
                
            ];

            Jira_Project__c project = JiraHelper.updateProjectRecord(queriedProject, projectData);

            update project;
        }
        catch(Exception e){
            System.debug(LoggingLevel.ERROR, 'Error processing project_updated event: ' + e.getMessage());
            CustomLogger.insertLog(e, LoggingLevel.ERROR);
            throw e;
        }
    }

    public void execute(System.QueueableContext context){
        process(payload);
    }
}